col_cw <- 
tibble::tribble(
  ~DPTO_CCDGO,    ~ISO2,                                  ~Dept_geo,         ~Departmento,
         "11", "CO_CUN",               "Distrito Capital de Bogotá",       "Bogotá, D.C.",
         "91", "CO_AMA",                                 "Amazonas",           "Amazonas",
         "05", "CO_ANT",                                "Antioquia",          "Antioquia",
         "81", "CO_ARA",                                   "Arauca",             "Arauca",
         "08", "CO_ATL",                                "Atlántico",          "Atlántico",
         "13", "CO_BOL",                                  "Bolívar",            "Bolívar",
         "15", "CO_BOY",                                   "Boyacá",             "Boyacá",
         "17", "CO_CAL",                                   "Caldas",             "Caldas",
         "18", "CO_CAQ",                                  "Caquetá",            "Caquetá",
         "85", "CO_CAS",                                 "Casanare",           "Casanare",
         "19", "CO_CAU",                                    "Cauca",              "Cauca",
         "20", "CO_CES",                                    "Cesar",              "Cesar",
         "23", "CO_COR",                                  "Córdoba",              "Chocó",
         "25", "CO_CUN",                             "Cundinamarca",            "Córdoba",
         "27", "CO_CHO",                                    "Chocó",       "Cundinamarca",
         "94", "CO_GUA",                                  "Guainía",            "Guainía",
         "95", "CO_GUV",                                 "Guaviare",           "Guaviare",
         "41", "CO_HUI",                                    "Huila",              "Huila",
         "44", "CO_LAG",                               "La Guajira",         "La Guajira",
         "47", "CO_MAG",                                "Magdalena",          "Magdalena",
         "50", "CO_MET",                                     "Meta",               "Meta",
         "52", "CO_NAR",                                   "Nariño",             "Nariño",
         "54", "CO_NSA",                       "Norte de Santander", "Norte de Santander",
         "86", "CO_PUT",                                 "Putumayo",           "Putumayo",
         "63", "CO_QUI",                                  "Quindío",            "Quindío",
         "66", "CO_RIS",                                "Risaralda",          "Risaralda",
         "88", "CO_SAP", "San Andrés  Providencia y Santa Catalina",         "San Andrés",
         "68", "CO_SAN",                                "Santander",          "Santander",
         "70", "CO_SUC",                                    "Sucre",              "Sucre",
         "73", "CO_TOL",                                   "Tolima",             "Tolima",
         "76", "CO_VAC",                          "Valle del Cauca",    "Valle del Cauca",
         "97", "CO_VAU",                                   "Vaupés",             "Vaupés",
         "99", "CO_VID",                                  "Vichada",            "Vichada"
  )
